### ISSUE TITLE
Cannot read property 'innerHTML' of null in ember test

### ISSUE THREAD

**Issue by markanton1726** [evocount/ember-tui-editor#195]
Hi.

The moment of running test in ember, in console chrome, i get error cannot read property 'innerHTML', specifically in this code block

```
this.render(hbs`
    {{person/person-item
        person=person}}
  `);
```
And the template

```
{{tui-editor
        data-autoid="person__item"
        value=person.description
        viewer=true}}
```

In the console chorme, appears this.

```
tui-editor-Editor.js:5712 Uncaught (in promise) TypeError: Cannot read property 'innerHTML' of null
    at new ToastUIEditorViewer (tui-editor-Editor.js:5712)
    at Function.factory (tui-editor-Editor.js:11412)
    at tui-editor.js:62
```

Thank you.

**Comment by ttill** [comment]
Hi, thanks for your report. Could you maybe provide a failing test? My first guess would be, that this is related to ember-tui-editor loading the tui-editor lazily.

**Comment by Samsinite** [comment]
We were actually getting this error at runtime causing the WYSIWYG to not work, but the MD editor still worked. Looks like the upgrade to 2.0 has fixed this issue for us.
