### ISSUE TITLE
Dependency seems to be incompatible with node 11

### ISSUE THREAD

**Issue by faridelnasire** [evocount/ember-tui-editor#197]
$ ember install ember-tui-editor

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Command failed: yarn add --dev ember-tui-editor --non-interactive
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning ember-tui-editor > ember-auto-import > typescript-memoize > core-js@2.4.1: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
error broccoli-postcss@3.5.3: The engine "node" is incompatible with this module. Expected version "^4.5 || ^6 || ^7 || ^8 || ^9 || ^10". Got "11.15.0"
error Found incompatible module.

yarn add v1.17.3
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Stack Trace and Error Report: /var/folders/1q/tzrdmh614s7_yfhz1t7l1jyr0000gn/T/error.dump.eb4ae3a6e3b86159984a83eebdeff492.log

**Comment by faridelnasire** [comment]
Got over this issue by running the following: `yarn add ember-tui-editor --ignore-engines`.

**Comment by ttill** [comment]
Great. I was unable to reproduce using npm.
