### ISSUE TITLE
TOAST UI Editor 2.0

### ISSUE THREAD

**Issue by jtjeferreira** [evocount/ember-tui-editor#252]
Hi! Thanks for this addon! 

Any plans to support version 2 https://ui.toast.com/weekly-pick/en_20200318/?

**Comment by ttill** [comment]
Thanks for bringing this up! I somehow completely missed the release of v2. Will have a look at it in the next days.

**Comment by ttill** [comment]
More or less done in 87bc30e3bf9a1724203b5525de4c9b6880bbfbd7, but before releasing I at least have to support loading language files, which are not bundled anymore.

**Comment by miguelcobain** [comment]
@ttill I'm not a huge fan of creating a helper just to load a locale file.

Wouldn't it be better to somehow have this locale file loading in the `setupEditor()` function?

My suggestion:

- in the `setupEditor()` you check the `@language` argument and, based on that, load the correct locale file.
- We could observe for changes on the `@language` argument in a special way (like we already do for "value"). That observer would load the new locale file and then call `setLanguage` with the new language.

This would make the `@language` argument a bound one, and we wouldn't need new helpers or to learn any new api whatsoever.
Am I missing something?

**Comment by miguelcobain** [comment]
Oh, was that because of the `ember-auto-import only supports dynamic import() with a string literal argument.`?
That's too bad. 😢

**Comment by miguelcobain** [comment]
I'm presenting an alternative to the helpers approach in https://github.com/evocount/ember-tui-editor/pull/267

**Comment by miguelcobain** [comment]
Thank you @ttill !

> Btw. we lost some features that are not bundled anymore with tui-editor directly…

What features are those?

**Comment by miguelcobain** [comment]
@ttill If we provide a `@plugins` argument, we can allow the user to import the plugins themselves. Here's how it would look with the UML plugin:

```js
import uml from '@toast-ui/editor-plugin-uml';

export default MyComponent extends Component {
  // ...
  plugins = [uml];
  //..
}
```

```hbs
<TuiEditor
  @plugins={{this.plugins}}
  @value={{this.value}}
  @onChange={{fn (mut this.value)}} />
```

I just followed the documentation at https://github.com/nhn/tui.editor/tree/master/plugins/uml basically.

We could provide the `@plugins` argument and add a section about it on the README, possibly with an example.

**Comment by ttill** [comment]
Incorporated this in v1.1.0. Thanks @miguelcobain
