### ISSUE TITLE
Missing peer dependency on @ember/test-helpers breaks with @ember/test-helpers > v4

### ISSUE THREAD

**Issue by jelhan** [evocount/ember-tui-editor#496]
```
ember-tui-editor tried to import "@ember/test-helpers" in "ember-tui-editor/test-support/helpers.js" from addon code, but "@ember/test-helpers" is a devDependency. You may need to move it into dependencies.
```

This error occurred when upgrading @ember/test-helpers to v4.

ember-tui-editor imports @ember/test-helpers here: https://github.com/evocount/ember-tui-editor/blob/46fbb23dd3f77f914950fe871d60a688a2187d7a/addon-test-support/helpers.js#L1

But it neither declares a dependency nor a peer dependency on @ember/test-helpers. Declaring a peer dependency should fix the issue.

**Comment by miguelcobain** [comment]
This should be fixed on version `4.0.0`. Please reopen if issue persists.
